version: "3.6"
services:
    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        ports:
            # queue + management console
            - "5672:5672"
            - "15672:15672"
    mongo:
        image: mongo:4.2
        ports:
            - "27017:27017"
        volumes:
            - "mongo:/data/db"

volumes:
    mongo:
